### ISSUE TITLE
VS2015 integration

### ISSUE THREAD

**Issue by wgebczyk** [daveaglick/Scripty#10]
I've given try to VS extension and Scripty.MSBuild. What I've observed:
- Simply installing VS extension and adding new file with extension "csx", does not result in solution explorer custom icon file and do not automatically set Custom Tool.
- After that adding NuGet Scripty.MSBuild does not result in adding file to solution.
- Settings manually custom tool in properties in VS2015, results in attaching generated file to solution explorer.
  Is that expected behavior?

**Comment by daveaglick** [comment]
Both of these observations are expected behavior:

**Visual Studio Extension (Custom Tool)**

Installing a custom tool as a vsix only registers a handler for a specific value in the "Custom Tool" property of a file. Setting the correct custom tool property value for a given file in the project is still a manual process. There's a couple reasons for this:
- The first is that a VS extension is global. That is, it gets installed for the IDE as a whole and not for an individual project. Along these lines, a _single file generator_ (the actual name for this type of extension, even though Scripty can actually generate multiple files) only gets "called" by Visual Studio when the custom tool property is configured to look at it. There's just no mechanism for a SFG extension to set the custom tool properties for all files in a project/solution automatically.
- Even if a SFG extension did have a chance to examine and set custom tool property values (perhaps on first load of each project after installation), I don't think this would make a good workflow in general. It's possible that other extensions know how to handle `.csx` files and we wouldn't want to override those settings. It's also possible that you have some `.csx` files in the project that aren't intended to be run through Scripty. Also possible that you only want some `.csx` files to use the custom tool extension and others to use the MSBuild extension since the former works at "design time" and the latter at compile time.

**MSBuild**

The MSBuild package installed a new MSBuild task into your project. Unlike the VS extension, this is project-specific and so we can automatically operate at a project level, processing all `.csx` files in the project (of course this behavior can be overridden in the MSBuild settings). Because the MSBuild task is part of the build process, it's not really appropriate to modify the actual project when it's run. The outputs will all be included in the compilation, they just won't get added to the project (though they can always be added manually, or by running the custom tool for the script, which is not mutually exclusive with the MSBuild task).

**Comment by Herdo** [comment]
Is there a special reason, that the file extension has to be `.csx`?
If not, why not introduce a custom file extension?
I'd prefer to keep the `*.csx`.

An alternative:
One would develop using both (Scripty.MsBuild [or Cake later on] and the Scripty VS extension).
The build itself won't modify the `*.csproj` file, so it won't need the extension.
However, due to the availability of  the extension to the developer, why not add an **Item Template** for Scripty files?

An Item Template would list in the "Add Item" dialog as the - in my opinion very awesome! - name `Scripty script`.
The extension would still be `.csx`, but the custom tool will be set automatically.
[This blog post](http://nickdarnell.com/visual-studio-item-template-custom-tool/?ModPagespeed=noscript) by Nick Darnell will make things easy.

As additional thought:
The Item Template might provide a basic body for templates, e.g. including #12 .

**Comment by daveaglick** [comment]
@Herdo

> Is there a special reason, that the file extension has to be .csx

This was done deliberately. I considered going with a custom extension, but .csx offered a number of benefits:
- It's already recognized by Visual Studio and other tooling as a Roslyn/scriptcs script and so syntax hi-lighting, Intellisense, etc. will automatically light up. We _could_ replicate this in Visual Studio for a different extension, but then there's lots of other tools like VS Code that also have this recognition built-in.
- While all Scripty scripts are not _necessarily_ generic C# scripts because of the globals, those that don't make use of the globals will also work with the normal C# script runner out of the box. In addition, all normal C# scripts are also Scripty scripts. This provides some nice interoperability when you want to design a script that is both usable from Scripty and from the C# script runner. Of course, you could specify a different extension for a script when sending it to the Roslyn or scriptcs script runner, but why make it more complicated?
- It's easy enough to control which `.csx` files get processed. For the MSBuild task you just opt-out by adjusting the included files glob. In fact, you could make it use an alternate extension just by changing the glob to look at all files with that other extension. The custom tool is opt-in to begin with since you have to set the custom tool property - and you can opt-in to any file, `.csx` extension or not.

> why not add an Item Template for Scripty files

This is an excellent idea! Tracking in #14.

**Comment by daveaglick** [comment]
@wgebczyk Do you have any more questions regarding the integration at this time?

**Comment by wgebczyk** [comment]
Sorry being late - no that answered my questions/thoughts. Thanks!

**Comment by daveaglick** [comment]
Np - feel free to open another issue if anything else comes up :smile:
