### ISSUE TITLE
Possible collaboration with CodeGeneration.Roslyn?

### ISSUE THREAD

**Issue by masaeedu** [daveaglick/Scripty#101]
@AArnott's [CodeGeneration.Roslyn](https://github.com/AArnott/CodeGeneration.Roslyn) is a project that solves the problem of integrating generated code seamlessly with MSBuild, so that Intellisense works as you edit (without having to manually include generated files in the project, or trigger a rebuild after save).

Scripty provides a far more convenient API for actually doing code generation, so it would be really nice if it were possible to combine the best aspects of both projects into one.

**Comment by StingyJack** [comment]
Can you be a bit more specific as to what you think should be incorporated? Scripty already has MSBuild tasks.

**Comment by daveaglick** [comment]
I think the two projects take fundamentally different approaches to code generation. Not that I'm opposed to collaboration where it makes sense, but I don't think it's possible or even helpful to try and combine them into one project - choice is good.

Also have the same question as @StingyJack - is there a specific aspect of the other project your especially interested in? Is it mostly the Intellisense that you're missing?

**Comment by masaeedu** [comment]
@daveaglick It is primarily the fact that the changes made in the MSBuild step are part of the editing experience (i.e. you get type checking/Intellisense). This is the "killer feature" for me; for most other things I can just use IL-rewriting or templating languages.

**Comment by masaeedu** [comment]
@daveaglick Could you provide a bit more info on what you see as the biggest differences between the code generation approaches of the two projects? I have a very surface level understanding, but as far as I can tell both ultimately produce additional C# files that are included in the compilation unit using MSBuild. 

The CodeGeneration.Roslyn project is a bit more strictly tied to the Roslyn API and provides syntax trees of attribute-marked classes as the input, while the Scripty API is more flexible and allows text-oriented codegen using documents as input, but from my limited understanding the resulting artifacts are very similar, i.e. additional C# files.

**Comment by AArnott** [comment]
To get the generated code to be included in VS intellisense may work for your project then. It may be as simple as arranging your msbuild targets such that the design time build includes the code gen step like CG.R does.

**Comment by StingyJack** [comment]
> the resulting artifacts are very similar, i.e. additional C# files.

They are whatever you want. Most of the time I dont use the default output file with scripty (or T4 files for that matter), as I need to generate code into several places from a single origin (a configuration file that emits new or updates existing code files for SQL db projects, class libraries, wcf service projects, asp.net projects, etc). 

Scripty makes this nice because it can be executed from a script in the same solution as those projects and I can get immediate feedback. T4 could do this too, but it cant leverage existing code in those projects easily, the editing sucks, and implementing a custom t4 host looked like it would need a lot of work (MS always seals the most useful to derive from classes).
