### ISSUE TITLE
Latest Visual Studio Version 15.3

### ISSUE THREAD

**Issue by zechamps97** [daveaglick/Scripty#111]
Project.Analysis.Documents is not populating correctly on the latest version of Visual Studio. It shows no files.

I work with @crash-dive who did some work on the Cake add in, we've just download the source and are going to make a bunch of fixes to make the tests work. Is it ok to send a pull request?

**Comment by daveaglick** [comment]
Yes, please! I don't get as much time as I would like on his project so any help is greatly appreciated.

**Comment by crash-dive** [comment]
We had a look at this and it was more complex than we first thought. The issue was not with Scripty but a deeper problem with how Roslyn cannot create MSBuildWorkspaces for projects that use the new csproj format. This is what caused our issue where the documents were always empty. I am still not 100% sure about another issue relating to the ToolsVersion however we are going to close this issue for now and then if we have a solution to the problem which requires Scripty to be updated we will open it again.

@zechamps97 can you close this because I do not have the rights to do so
