### ISSUE TITLE
Making Scripty.MsBuild run only within a single build configuration

### ISSUE THREAD

**Issue by ravindUwU** [daveaglick/Scripty#118]
A project I'm working on uses Scripty for generating C# files, but it doesn't need to do so very often as it can utilize the files that were previously generated.

Is it possible to make Scripty run only within a particular build configuration?

I presume the solution would be to either,
1. Declare `Scripty.MsBuild` as a dependency for a particular build configuration, which I'm not sure if is even possible 😛
2. Making the Scripty MSBuild task run only within a particular build configuration.

This can be accomplished with Cake and its build Targets, but I was wondering if there was a way to do this without it.

**Comment by daveaglick** [comment]
The best way to do this is going to be to add a condition to the Scripty MSBuild target. Once you install the Scripty.MsBuild package you're project file should end up with a line like this near the end:

```
<Import
  Project="..\..\..\packages\Scripty.MsBuild.0.7.3\build\Scripty.MsBuild.targets"
  Condition="Exists('..\..\..\packages\Scripty.MsBuild.0.7.3\build\Scripty.MsBuild.targets')" />
```

You'll need to add an extra condition to the target import for configuration, something like:

```
<Import
  Project="..\..\..\packages\Scripty.MsBuild.0.7.3\build\Scripty.MsBuild.targets"
  Condition="Exists('..\..\..\packages\Scripty.MsBuild.0.7.3\build\Scripty.MsBuild.targets') AND '$(Configuration)' == 'Release'" />
```

**Comment by ravindUwU** [comment]
The aforementioned project is a .NET Standard class library, which I'm using VS 2017 to build. The `<Import>` statements do not get added when I install the `Scripty.MsBuild` package...

```XML
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard1.3</TargetFramework>
	</PropertyGroup>
	<ItemGroup>
		<!-- ... -->
		<PackageReference Include="Scripty.MsBuild" Version="0.7.4" />
	</ItemGroup>
</Project>
```

As I understand, `<Import>` statements aren't supported in the new csproj format: http://www.natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/#must-delete

**Comment by CZEMacLeod** [comment]
@RavinduL the imports do get created in under SDK based projects - just in the obj folder and are autogenerated if missing.

@daveaglick I noticed in the [Scripty.MsBuild.targets](https://github.com/daveaglick/Scripty/blob/develop/src/Scripty.MsBuild/Scripty.MsBuild.targets) file a property EvaluateScriptyFiles that does not seem to get used - perhaps this should be the condition for the EvaluateScriptyFiles target on line 30?
`<Target Name="EvaluateScriptyFiles" DependsOnTargets="_ResolveScriptyFiles" BeforeTargets="BeforeBuild" Condition=" '$(EvaluateScriptyFiles)'=='true' ">`

If this was the case the problem could be solved with
```
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard1.3</TargetFramework>
	</PropertyGroup>
	<PropertyGroup>
		<EvaluateScriptyFiles Condition=" '$(Configuration)' != 'Release' ">false</EvaluateScriptyFiles>
	</PropertyGroup>
	<ItemGroup>
		<!-- ... -->
		<PackageReference Include="Scripty.MsBuild" Version="0.7.5" />
	</ItemGroup>
</Project>
```

**Comment by ravindUwU** [comment]
@CZEMacLeod does this mean that there is no way to conditionally import the Scripty build targets in a .NET Core / Standard project? Furthermore, are you referring to .NET Core / Standard / projects with the new csproj format, by the use of the term 'SDK based project'?

**Comment by CZEMacLeod** [comment]
@RavinduL The new project format starts with `<Project Sdk="Microsoft.NET.Sdk">` and can target the full Net Framework e.g. 4.6.1 just as easily as net core or standard.
The new format uses <PackageReference> (although you can use these in the older format too now) instead of packages.config and when you do so, a number of files get created under obj when it resolves and installs the packaged.
Specifically proj.nuget.g.props and proj.nuget.g.targets files which get auto-imported 'before' and 'after' the main proj file instead writing them into the proj file as the older system did.
Hence you can't change the import command as you suggested as it will get overwritten. It would have been overwritten if you updated the package previously anyway.

A better solution would be for the scripty targets file to conditionally run.
To work around this for now try something like 
```
<Target Name="ConditionalScripty" DependsOnTargets="_ResolveScriptyFiles" BeforeTargets="EvaluateScriptyFiles">
	<ScriptyFile Remove="@(ScriptyFile)" Condition="'$(Configuration)'!='Release'" />
</Target>
```
I have not tested this but basically it should remove the list of detected scripty files to run after it detects them but before it runs them _unless_ the configuration is set to release (or whatever).
You could even just clear the list entirely everytime and then add the specific files you want to run in each circumstance... even using globbing..
```
	<ScriptyFile Remove="@(ScriptyFile)" />
	<ScriptyFile Include="**\Scripts\Release\*.csx" Condition="'$(Configuration)'=='Release'" />
	<ScriptyFile Include="**\Scripts\Debug\*.csx" Condition="'$(Configuration)'=='Debug'" />
```
or even
```
	<ScriptyFile Remove="@(ScriptyFile)" />
	<ScriptyFile Include="**\Scripts\$(Configuration)\*.csx" />
```
