### ISSUE TITLE
Scripty Extension Page Not Found

### ISSUE THREAD

**Issue by JayJeckel** [daveaglick/Scripty#129]
I wanted to download the Scripty Visual Studio Extension, but the link in the repo's readme (https://visualstudiogallery.msdn.microsoft.com/52c02bb2-1d79-476e-82fb-5abfbfe6b3e4) leads to a "We're sorry, the page you requested cannot be found!" or sometimes a 404 error. Is there somewhere else to download the vsix package or is there something else I might be missing?

EDIT: I also searched 'Scripty' in the Tools -> Extensions and Updates dialog of both VS 2015 and 2017, but no results were found.

**Comment by daveaglick** [comment]
Sorry about that. I removed it for now. Scripty is in need of an update (which I fully intend to do sometime this year), but in the meantime there were reports of the vsix breaking Visual Studio. Since I don't have time to look closer at it right now, I unlisted the package lest it get swamped with bad reviews. The MSBuild package should still work though, and you could build the vsix from source and locally install it if you really need to.

Keep an eye out for a new Scripty rewrite, probably sometime in the last couple months of the year.
