### ISSUE TITLE
Clarify installation and first-use instructions (especially VS extension vs. NuGet package)

### ISSUE THREAD

**Issue by mmkal** [daveaglick/Scripty#43]
I am, most likely, being thick here. But adding the NuGet package (actually, all three of them) seems to have no effect. I've added it to a regular Class Library project on .NET 4.6. I also installed the Roslyn SDK to Visual Studio, and added the Microsoft.CodeAnalysis.CSharp.Scripting project. I've never actually used any Roslyn tools so I'm sure I'm missing something obvious. 

What switch do I need to flick to make it start doing its thing? My goal is to press Ctrl+Shift+B and my generated code to magically appear. Can I do that? I'd like to avoid installing the extension as I would like to be able to onboard new team members without them having to install it too.

**Comment by daveaglick** [comment]
You actually shouldn't need to install the Roslyn SDK or manually add any of the Roslyn packages or projects to the solution. Everything is self contained in the Scripty extensions and packages.

There are two different ways to use Scripty, and they can be used together or separately depending on your use case.

The first is to use the "custom tool" functionality contained in the `Scripty.CustomTool` Visual Studio extension at https://visualstudiogallery.msdn.microsoft.com/52c02bb2-1d79-476e-82fb-5abfbfe6b3e4. Just add that extension to Visual Studio and it's ready to go. Once the extension is installed, you have to "turn it on" for specific files. You do this by manually entering `ScriptyGenerator` as the "Custom Tool" for a file in the project (presumably a `.csx` file, though it'll work for any extension). The "Custom Tool" setting can be found in the file properties in Visual Studio. Once that's set, just right-click on the file and select "Run Custom Tool". Note that the scripts _will not_ be evaluated on every build automatically with the custom tool.

The other way to use Scripty is with the MSBuild task. In this case, add the `Scripty.MsBuild` NuGet package to your project. It will automatically pick up any `.csx` files in your project at build time, evaluate them, and add the results to your compilation. *You won't actually see the results in your project`. If you want the output of the scripts to show up in the project after using the MSBuild task, you'll need to manually add them after the first build.

I'd recommend looking at the `Scripty.CustomTool` first since it's more obvious when the generation happens and you can immediately see the results. Then once you're comfortable, maybe experiment with the build task.

**Comment by managedcoder** [comment]
I am not sure if this is what @mmkal is experiencing but I had the beginner experience of first adding the NuGet package, then recreating the example found here: http://daveaglick.com/posts/announcing-scripty?utm_source=twitterfeed&utm_medium=facebook and finding that nothing was happening.  It wasn't until I tried to right-click the .csx file and "Run custom tool" that I realized that the ScriptyGenerator was not installed.  That one is not a NuGet package install so once I installed the Scripty extension (Tools | Extensions and Updates | enter 'Scripty' in search and then install) everything worked.

**Comment by daveaglick** [comment]
@managedcoder Very good point, thanks! I mistyped above and said to install the `Scripty.CustomTool` NuGet package, but that's not a NuGet package at all - it's a Visual Studio extension available here: https://visualstudiogallery.msdn.microsoft.com/52c02bb2-1d79-476e-82fb-5abfbfe6b3e4

**Comment by daveaglick** [comment]
FYI - I'll update the documentation to try and make this process a little clearer given the experience you both had.
