### ISSUE TITLE
Trying to call a method of a class from Project.Analysis.Documents

### ISSUE THREAD

**Issue by managedcoder** [daveaglick/Scripty#46]
I can get the SyntaxNode for the class I want from the SemanticModel of Project.Analysis.Documents as well as the SyntaxNode for the method I want and I would like to dynamically call that method by using SemanticModel.GetOperation(methodSyntaxNode) but when I do I get an exception:

Custom tool error: System.InvalidOperationException: Feature 'IOperation' is disabled.

Is this the correct way to calling the method (a static public property actually)?  How Should I do this?

-Russ

**Comment by daveaglick** [comment]
A couple things going on here, I think.

The first is that `IOperation` appears to be an "unshipped" API (at least for the version of Roslyn we're currently using). See https://github.com/dotnet/roslyn-analyzers/issues/1028#issuecomment-221929032 and http://david.gardiner.net.au/2016/08/error-ad0001-compiler-analyzer-threw.html. Unfortunately, I can't currently update Roslyn due to compatibility concerns with VSIX and MsBuild tasks and I don't want to manually enable an unshipped feature.

Secondly though, I'm not sure this is actually going to do what you want anyway. When you say you're trying to call a method, do you mean you want to evaluate something that's part of your project (and not the Scripty script)? If so, that gets tricky anyway. Scripty runs in it's own process space and the scripts are evaluated at build-time (or design-time if using the custom tool). At that stage, your own application is just a collection of source code. In fact, your own application hasn't even been compiled into an assembly yet (at least not beyond what Roslyn does to construct the workspace) so there really isn't a "static public property" to call yet (at least not in the sense that there's associated IL that can be evaluated). Hopefully that made sense...

**Comment by managedcoder** [comment]
@daveaglick,
Bummer about the unshipped IOperation API!  Let me explain quickly what I am trying to do which will provide some context and address your second point.  I have a VS project template that produces an Azure Mobile App that has authentication, push notification, and data sync for offline usage all wired up in a way that allows the developer to choose which features/capabilities they want to light up.  Depending on what the developer wants to light up, certain SDK types will be different (IMobileServiceTable or IMobileServiceSyncTable, for example) so I am using Scripty to generate the proper types in a partial class depending on how a Capabilities class is configured.  This is the same Capabilities class is used by the project code generated by the project template which directs the boiler plate code in proper operation depending on what capabilities are desired (e.g. check the push notification capability in boiler plate code before attempting to send a push notification because dev may not have choosen to configure PN for the app).  

So this needs to be a build-time code generation scenario so that when the developer chooses the capabilities they want the proper code is generated for the partial class that has proper types and such generated.  If the developer later changes their mind and decides to light up push notifications or offline data sync support the proper code will be generated on the next build.

**Comment by daveaglick** [comment]
I can think of three ways this could potentially be tackled:
- Put the `Capabilities` class in a separate library that gets consumed both by your application and by Scripty using an `#r` directive. If you do that, Scripty has access to any objects in the referenced library the same way any code would and can evaluate whatever you need it to.
- Place the configuration inside a JSON/XML/text/etc file that both Scripty and your application can read. Have Scripty read it and then generate what's needed based on it's content. Your application could read it and then instantiate or otherwise initialize whatever state you need to based on it.
- Use the semantic model to see what the `Capabilities` class looks like. You won't be able to evaluate anything, but if you're just trying to figure out what it contains, you shouldn't need to.

Hopefully one of these approaches will get you what you need!
