### ISSUE TITLE
Can an assembly reference dynamically use the Solution configuration (Debug/Release)?

### ISSUE THREAD

**Issue by davidaramant** [daveaglick/Scripty#48]
A previous issue (#9) showed how to reference another DLL in the same solution.  However, the example hardcoded the configuration type in the path to `Release`.

Is there a way to dynamically reference the configuration type in the include?  In T4 you can do this:
`<#@ assembly name="$(SolutionDir)OtherProject\bin\$(Configuration)\OtherAssembly.dll" #>`

This is difficult to search for because "Configuration" is such a generic term.

**Comment by daveaglick** [comment]
Ideally I think you'd want to reference the assembly from its source location rather than the build output. I.e., if it's coming from a NuGet package then you'd want to path to the assembly to point to the "packages" folder at the root of your solution. 

I actually wouldn't recommend doing what's described in #9. Trying to reference the result of a build of the project that a script is in (or another project in the same solution) will be unreliable. Because Scripty is run as part of the build process, the result of the current build isn't available until after Scripty is done. If you do reference an assembly from the current project or another one from the same solution, it'll probably be from a previous build.

To answer your specific question - unfortunately it's not possible even if you wanted to. The preprocessor directives like `#r` are evaluated when the script is first processed. At this stage we haven't loaded the current project and solution yet. In fact, they may never be loaded as an optimization because not all scripts need to introspect the current project/solution. If the `Project` global property is never referenced in the script, the project and solution will never be evaluated.

**Comment by StingyJack** [comment]
pr #76 would resolve some of this by #load-ing the .cs instead of #r-ing it.
