### ISSUE TITLE
VS2015: Unable to find Custom Tool property when looking at Properties for the .csx (or any file)

### ISSUE THREAD

**Issue by yilativ** [daveaglick/Scripty#49]
Do we know of a way to set this in a Visual Studio project with a project.config?

I do not see a way to set the MSBuild, maybe there is a way to set this with the Scripty CLI ?

Did read this, but didn't help me identify how to get this working. 

Thanks!
Really anxious to replace my T4 templates with Scripty.

**Comment by daveaglick** [comment]
This is a great question. The `Scripty.CustomTool` library and corresponding "Custom Tool" is something called a _single file generator_ (even though you can actually create more than one file as output). In the traditional .csproj format you could set a specific single file generator on a per-file basis. It appears as though this kind of support for single file generators hasn't made it into .NET Core yet (see aspnet/Tooling#322 and aspnet/Tooling#394). The .NET team is aware of the issue though so a fix may be forthcoming (I've asked for clarification).

I've intentionally not focused on .NET Core scenarios for Scripty yet since the Core tooling is still in "preview". There's enough to do without spending energy on chasing that moving target. Once the tooling reaches release, I'll start taking a look at how Scripty can (and can't) work for .NET Core projects.

In the meantime, you _may_ be able to run Scripty scripts in a .NET Core project using the Scripty CLI (or the Scripty Cake extension if you want to instrument your build with Cake). It'll certainly process the scripts. What I'm not so sure about is whether both Roslyn and MsBuild will be able to compile the project which is necessary to provide project information to the Scripty script. If you try it out, let me know how it goes!

I'm going to close this issue for now since it's not clear if/when .NET Core is going to get support for single file generators and the Visual Studio Custom Tool file property.
