### ISSUE TITLE
Default file is compiled but not added to the project.

### ISSUE THREAD

**Issue by SERWare** [daveaglick/Scripty#51]
I'm using the NuGet package and the file that is created by default is compiled but not added to the project (even establishing "Output.BuildAction = BuildAction.Compile;").

**Comment by daveaglick** [comment]
This is by design. The NuGet package contains an MsBuild task that runs on every build. At this stage in the pipeline, MsBuild tasks have the ability to influence what the build engine sees but cannot actually change the project file(s) included in the build. There are two ways to get the generated output into your project:
- Run a build once to generate the file initially and then manually include it in the project.
- Use the Scripty Visual Studio extension in addition to (or instead of) the NuGet package to get "design-time" code generation. When you use the extension and run it as a custom tool in Visual Studio, the output files are automatically added to the project.

**Comment by SERWare** [comment]
That clarifies an important difference between the package and the tool.

Thanks for Scripty and your answer.

**Comment by daveaglick** [comment]
No problem!
