### ISSUE TITLE
No "file properties" windows with .net core projects

### ISSUE THREAD

**Issue by ducman** [daveaglick/Scripty#59]
I was going to try scripty out over t4 but I'm unable to access the "custom tool" from the file properties window. It actually doesn't even show up. I'm not sure if it's me.

It is some what similar to this issue: `http://stackoverflow.com/questions/34314146/visual-studio-2015-cant-change-access-modifier-of-new-resources-files`
It look just like the screenshot with File Name and Full Path and that's it. As a matter of fact, it shows like this for every file.

This seem to render scripty useless. Anyway to work around this without going msbuild/cli?

**Comment by daveaglick** [comment]
Unfortunately no workaround right now. See [this comment](https://github.com/daveaglick/Scripty/issues/49#issuecomment-244487701) on an earlier issue. TL;DR: .NET Core does not support single file generators like Scripty at this time.

You may still be able to use the MSBuild task, but I haven't tested it on Core yet because I'm waiting for the tooling to stabilize before spending too much time on it.
