### ISSUE TITLE
Can not add external assembly reference in script file

### ISSUE THREAD

**Issue by paramhq** [daveaglick/Scripty#60]
![screenshot_2](https://cloud.githubusercontent.com/assets/3767382/20597277/bc5a51b2-b268-11e6-8732-15e3432c0100.png)

I need to print table names in a text file, for that I have written "Text.csx", upon running script file I get the following error.
"The type or namespace name 'SqlServer' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)"

I have already added required assemblies references in project. Need your help desperately.

**Comment by daveaglick** [comment]
I'm glad you found the GitHub repo, I'd be happy to help (and thanks for updating your gallery comment!).

The scripts are evaluated *outside* the context of your project since they need to compile it independently. An interesting enhancement would be for the scripts to automatically load any references the host project contains (I've added this as issue #61). In the meantime, you have to tell Scripty what assemblies to use and where they're located. You do this with the `#r` preprocessor directive. [This article from the scriptcs project](https://github.com/scriptcs/scriptcs/wiki/Writing-a-script#referencing-assemblies) describes how that looks (note scriptcs and Scripty both use Roslyn under the hood, so it works the same way in Scripty).

In your case, I'm guessing you need something like `#r "Microsoft.SqlServer.Smo.dll"` at the top of your script (you might also need the full path if that assembly isn't in the GAC).

**Comment by paramhq** [comment]
I have added the above line `#r "Microsoft.SqlServer.Smo.dll"` and imported namespace but it is still not working.

**Comment by daveaglick** [comment]
Do you get any errors? Try finding the "Microsoft.SqlServer.Smo.dll" assembly on your disk and using an absolute path - if that works then we know the problems are due to the assembly location and we can figure out the correct relative path to use.

**Comment by paramhq** [comment]
```
#r "C:\\Program Files\\Microsoft SQL Server\\120\\SDK\\Assemblies\\Microsoft.SqlServer.Smo.dll"
#r "C:\\Program Files\\Microsoft SQL Server\\120\\SDK\\Assemblies\\Microsoft.SqlServer.ConnectionInfo.dll"

using System;
using Microsoft.SqlServer.Management.Smo;
```
bingo....!!! yes, it works if I use absolute path.

**Comment by daveaglick** [comment]
Okay, great! So now we know that the script code is fine and it's just a matter of getting the path to the assembly correct. Since that assembly looks like it's distributed with SQL Server, I think you're going to have to go ahead and keep the absolute path (unless you want to actually copy the assembly somewhere inside your solution folder).
