### ISSUE TITLE
Getting the DTE from the available ScriptContext

### ISSUE THREAD

**Issue by StingyJack** [daveaglick/Scripty#63]
Is there a way to get the DTE or at least current active solution build configuration?

I use a specific solution configuration to circumvent the "Regenerate on Save" functionality in T4, and would like to use the same indicator in csx that are part of the project. 

I've been poking at the various Project-y objects but its been slow and painful without a debugger or other live inspectable.

Example of the T4 circumvention - if SlnConfig not "RegenCodeFiles", emit the existing file back to T4 host/engine.
```
var _ServiceProvider = Host as IServiceProvider;
var _Dte = _ServiceProvider.GetService(typeof(SDTE)) as DTE;
var _ConfigName = _Dte.Solution.SolutionBuild.ActiveConfiguration.Name;

var _RegenerateFile = "RegenCodeFiles".Equals(_ConfigName, StringComparison.OrdinalIgnoreCase);

if (_RegenerateFile == false)
{
	Debug.WriteLine($"Not Regenerating File");
	var existingFileName = Path.ChangeExtension(Host.TemplateFile, "cs"); 
	var fileContent = File.ReadAllText(existingFileName);
	return fileContent;
}

```

**Comment by reduckted** [comment]
Given that the core of Scripty runs using Roslyn and can therefore be run using just MSBuild (and does not require Visual Studio), you won't be able to get access to the DTE object.

It sounds like you might need access to project properties (see #39), but it's not quite clear to me what you're trying to achieve. Do you have an example of what your `csx` file would look like if you hypothetically did have access to the DTE object?

**Comment by StingyJack** [comment]
im trying to avoid VS triggering custom tools and regenerating code when im not expecting it. 

I gave an example of how i can use a specific solution configuration to circumvent this in T4 templates, but the best i can come up with is a conditional compilation that throws an exception. my generated output still gets overwritten, however.

if there is a way to get the active configuration (debug, release, regencodefiles), and have the outfile not overwrite when ex is thrown, that would be what i am trying to get

**Comment by reduckted** [comment]
You could throw an exception, but the downside to that is you'd end up with compiler errors in the Error List, which would be annoying.

I guess your `csx` file could be something like this (it may or may not compile as is 😄):

    var canOutput = Context.Project.Build.GetPropertyValue("SkipCodeGeneration");

    if (!canOutput)  // You'll probably need to coerce the property value to a bool somewhere.
    {
        // Get the file name of the default output file.
        var fileName = IO.Path.ChangeExtension(Context.ScriptFilePath, ".cs");

        // Write the current contents to the default output so 
        // that the custom tool doesn't delete or change the default output file.
        Context.Output.Write(IO.File.ReadAllText(fileName));

        // Exit so that the default generation doesn't occur.
        return;
    }

    // Do your default code generation...

So at the start of the `csx` file, you check if you should skip code generation using a project property (which you can define in the `csproj` file when your "RegenCodeFiles" project configuration is used. Then, if you should skip code generation,  you read the contents of the existing generated file, then write that to the output. You need to do this because:
1. If you don't write anything and just exit, the custom tool will delete the existing generated file.
2. Anything you write to the output stream will replace the existing generated file.

The only downside to this is that you need access to the project properties, and (as per #39) they don't yet flow through to Scripty. I've actually made changes to fix that problem and I've been meaning to create a PR for it. Keep an eye on #39, because if I get some time in the next few days, I'll create that PR.

**Comment by daveaglick** [comment]
> if I get some time in the next few days, I'll create that PR.

...and I'd be happy to merge it :shipit: 

Thanks for the community support on this issue, @reduckted

**Comment by StingyJack** [comment]
Throwing the exception and clicking through Roslyn stuff for what I wanted is where i got to before I figured I should ask
![image](https://cloud.githubusercontent.com/assets/15381181/22190869/580ae572-e0f4-11e6-9fae-8e7720f248bb.png)

I can use with the conditional compilation symbols in lieu of project properties. I just wanted something that worked with the T4's that are already in place (and I wanted to try scripty)



Thanks for the follow up and the info.
