### ISSUE TITLE
Custom Tool not working in .NET Standard Class Library project, VS 2017.

### ISSUE THREAD

**Issue by salmelo** [daveaglick/Scripty#82]
I have a Class Library (.NET Standard) project, for which the Scripty custom tool is not doing anything at all. It works just fine in a WPF project under the same solution. Both projects were created from VS 2017, in case that matters.

I *think* this is because they added a new project type GUID, tho I couldn't tell you for sure. For reference, the project type GUID of the project in question is `9A19103F-16F7-4668-BE54-9A1E7A4F7556`.

**Comment by salmelo** [comment]
Updated VS and the GUID is back to the regular C# one, Custom Tool still isn't running tho. No idea.

**Comment by daveaglick** [comment]
See #49 - .NET Core projects do not currently support Single File Generators which is the extension mechanism the Scripty custom tool uses within Visual Studio. It's unclear whether that support will ever come to Visual Studio for .NET Core projects in the future.

In the meantime, you're stuck with running Scripty as an MSBuild task and manually adding the output files to your project (which is easier in .NET Core since the new csproj format has better support for wildcard source inclusion). You could also run Scripty outside MSBuild as an executable as part of your build pipeline. Regardless, until VS adds back support for Single File Generators, the Scripty custom tool won't work.

**Comment by CZEMacLeod** [comment]
I like Scripty as an MSBuild task better anyway - it means it can run on our build servers and that the output files are always up to date.

**Comment by JCKodel** [comment]
.net standard Projects have the same issue.
A .net standard .csproj have only this content:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
  </PropertyGroup>
</Project>
```
