### ISSUE TITLE
Scripty.MSBuild 0.7.1 doesn't work with .NET Framework projects

### ISSUE THREAD

**Issue by TylerBrinkley** [daveaglick/Scripty#84]
I cannot upgrade to 0.7.1 as it's dependent on `System.IO.FileSystem.Primitives` which Visual Studio says is not able to install into a project that targets .NET 4.5.

**Comment by daveaglick** [comment]
Oh, ffs (not aimed at you). The amount of time I've spent wrestling with dependencies and binding on this project is ridiculous. I'm assuming this is the MSBuild NuGet package (and not the VS extension)? I may be able to remove that dependency since it gets copied over as an assembly with the Scripty executable and the MSBuild task just shells out.

I'll get a test package up on MyGet if you wouldn't mind taking it for a spin to make sure there aren't any other dependency issues in 4.5 projects. It might be a few days though...

**Comment by TylerBrinkley** [comment]
Yes, this is with the MSBuild NuGet package. I'd gladly test it for you if you get it up on MyGet.

**Comment by dahauns** [comment]
Same issue here, but with the custom tool/VS extension.
And I foolishly already did the update...any way to download the old VSIX somewhere, or do I have to compile it myself?

**Comment by daveaglick** [comment]
@dahauns Are you specifically getting an error about `System.IO.FileSystem.Primitives`? I wouldn't expect you to see something like that with the custom tool. If not, what is the specific error you're seeing?

**Comment by dahauns** [comment]
Sorry, no, it's `System.IO.Filesystem`. The error (thrown in Microsoft.CodeAnalysis) states that it can't find the assembly with Version 4.0.1.0. (IIRC the latest Scripty builds include 4.0.2.0)
It's VS2015U3 with a .NET4.5.1 project. 

I also experimented with different versions of `Microsoft.Net.Compilers` in the project, but that just lead to different dependency problems (mainly with `System.Collections.Immutable` 1.2.0.0 <->1.3.0.0)

Speaking from memory here - I don't have access to my work machine/codebase before monday, I will get back to you with more specifics then.

**Comment by daveaglick** [comment]
@dahauns That's very helpful, thanks. I swear all these dependency binding problems with the latest .NET bits are going to send me to an early grave.

**Comment by daveaglick** [comment]
@TylerBrinkley Your issue with System.IO.FileSystem.Primitives should be resolved with 0.7.2 which I am about to release.

@dahauns If you're still having trouble after this release, can you please open a new issue so we can track your binding problem separately.
