### ISSUE TITLE
How to reference external assembly from file

### ISSUE THREAD

**Issue by wgebczyk** [daveaglick/Scripty#9]
How to add reference to some assembly file in non-locking way?
Like reference from one project another one and still be able to compile the referenced one without failure?

**Comment by daveaglick** [comment]
I'd be happy to help, but I'm not totally clear on the question. Generally, adding assembly references doesn't introduce a file lock. That's why multiple applications can be running and accessing assemblies in the GAC at the same time.

To introduce an assembly reference in your script, you can use the `#r` syntax. For example:

```
#r "..\\SomeOtherProject\\bin\\Release\\MyAssembly.dll"

// Rest of script that uses MyAssembly.dll
```

Does that answer your question?

**Comment by wgebczyk** [comment]
Yes, Seems to work as expected on small project. Thanks!

**Comment by daveaglick** [comment]
That's great to hear! Despite high interest, I haven't heard much back one way or the other from users yet. Glad to hear it's working as intended in your case.
